repos:
- repo: local
  hooks:
  - id: winipedia-utils
    name: winipedia-utils
    entry: poetry run python -m winipedia_utils.dev.setup
    language: system
    always_run: true
    pass_filenames: false
