name: Health Check Workflow
'on':
  workflow_dispatch: {}
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 6 * * *
permissions: {}
run-name: Health Check Workflow
defaults:
  run:
    shell: bash
jobs:
  health_check_matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.12'
        - '3.13'
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Add Poetry To Windows Path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: ${{ runner.os }} == 'Windows'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install --with dev
    - name: Update Dependencies
      id: update_dependencies
      run: poetry update --with dev
    - name: Add Dependency Updates To Git
      id: add_dependency_updates_to_git
      run: git add pyproject.toml poetry.lock
    - name: Setup Keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: Install Pyside System Dependencies
      id: install_pyside_system_dependencies
      run: sudo apt-get update && sudo apt-get install -y libegl1 libpulse0
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      if: runner.os == 'Linux'
    - name: Protect Repository
      id: protect_repository
      run: poetry run python -m winipedia_utils.dev.git.github.repo.protect
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Run Pre Commit Hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files
    - name: Run Tests
      id: run_tests
      run: poetry run pytest --log-cli-level=INFO
      env:
        QT_QPA_PLATFORM: offscreen
        QTWEBENGINE_DISABLE_SANDBOX: '1'
        QTWEBENGINE_CHROMIUM_FLAGS: --no-sandbox --disable-gpu --disable-software-rasterizer
          --disable-dev-shm-usage
  health_check:
    needs:
    - health_check_matrix
    runs-on: ubuntu-latest
    steps:
    - name: Aggregate Matrix Results
      id: aggregate_matrix_results
      run: echo 'Aggregating matrix results into one job.'
