name: Release Workflow
'on':
  push:
    branches:
    - main
  workflow_dispatch: {}
  schedule:
  - cron: 0 6 * * 2
permissions:
  contents: write
run-name: Release Workflow
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Setup Git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13'
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install Dependencies
      run: poetry install
    - name: Install Qt Dependencies
      run: sudo apt-get install -y libegl1 libgl1 libpulse0 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libnss3 libxrandr2 libxrender1 libxss1 libxtst6 libglib2.0-0 fonts-liberation alsa-utils xvfb libxshmfence1 libxcb1 libxcb-shm0 libatk-bridge2.0-0 libatspi2.0-0 libwayland-client0 libwayland-cursor0 mesa-utils
    - name: Protect Repository
      run: poetry run python -m winipedia_utils.git.github.repo.protect
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Run Hooks
      run: xvfb-run -a poetry run pre-commit run --all-files --verbose
    - name: Commit added changes
      run: 'git commit --no-verify -m ''[skip ci] CI/CD: Committing possible added
        changes (e.g.: pyproject.toml and poetry.lock)'''
      env:
        QT_QPA_PLATFORM: offscreen
    - name: Extract Version from pyproject.toml
      id: version
      run: 'version=$(poetry version -s) && echo "Project version: $version" && echo
        "version=v$version" >> $GITHUB_OUTPUT'
    - name: Tag and Push
      run: git push && git tag ${{ steps.version.outputs.version }} && git push origin
        ${{ steps.version.outputs.version }}
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@develop
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      uses: ncipollo/release-action@main
      with:
        tag: ${{ steps.version.outputs.version }}
        name: ${{ github.event.repository.name }} ${{ steps.version.outputs.version
          }}
        body: ${{ steps.build_changelog.outputs.changelog }}
