name: Test Workflow
'on':
  workflow_dispatch: {}
  
permissions:
  contents: write
run-name: Test Workflow
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Setup Git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13'
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install Dependencies
      run: poetry install
    - name: Install PySide6 System Dependencies
      run: sudo apt-get update && sudo apt-get install -y libegl1 libxrender1 libxext6 libgl1-mesa-glx libgl1-mesa-dev libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxkbcommon-x11-0 libx11-xcb1
    - name: Create Tests
      run: poetry run python -m winipedia_utils.testing.create_tests
    - name: Run Tests
      run: poetry run pytest
